In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [19]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=0)

In [20]:
X_train.shape, y_train.shape

((120, 4), (120,))

In [21]:
X_test.shape, y_test.shape

((30, 4), (30,))

In [58]:
clf = svm.SVC(kernel='rbf', gamma=1, C=10).fit(X_train, y_train)
clf.score(X_test, y_test)                    

1.0

In [48]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, iris.data, iris.target, cv=10)
scores 

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       1.        , 0.93333333, 1.        , 1.        , 1.        ])

In [49]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.97 (+/- 0.09)


In [56]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='rbf', gamma=0.1, C=10)
scores = cross_val_score(clf, iris.data, iris.target, cv=10)
scores 

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       1.        , 0.93333333, 1.        , 1.        , 1.        ])

In [57]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.98 (+/- 0.06)


In [54]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='rbf', gamma=1, C=10)
scores = cross_val_score(clf, iris.data, iris.target, cv=10)
scores 

array([1.        , 0.93333333, 1.        , 0.93333333, 0.86666667,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [55]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.10)


In [30]:
from sklearn import metrics
scores = cross_val_score(clf, iris.data, iris.target, cv=10, scoring='f1_macro')
scores

array([1.        , 0.93265993, 1.        , 1.        , 0.86111111,
       1.        , 0.93265993, 1.        , 1.        , 1.        ])

In [26]:
from sklearn.model_selection import ShuffleSplit
n_samples = iris.data.shape[0]
cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([1.        , 1.        , 1.        , 1.        , 0.96666667,
       1.        , 0.96666667, 1.        , 1.        , 1.        ])

In [12]:
def custom_cv_2folds(X):
    n = X.shape[0]
    i = 1
    while i <= 2:
        idx = np.arange(n * (i - 1) / 2, n * i / 2, dtype=int)
        yield idx, idx
        i += 1

custom_cv = custom_cv_2folds(iris.data)
(clf, iris.data, iris.target, cv=custom_cv)

SyntaxError: invalid syntax (<ipython-input-12-3a9c2b5fe0b9>, line 10)

In [14]:
from sklearn import preprocessing
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test)
clf.score(X_test_transformed, y_test)

0.9333333333333333

In [15]:
from sklearn.pipeline import make_pipeline
clf = make_pipeline(preprocessing.StandardScaler(), svm.SVC(C=1))
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([0.97777778, 0.93333333, 0.95555556, 0.93333333, 0.97777778])

In [16]:
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
scoring = ['precision_macro', 'recall_macro']
clf = svm.SVC(kernel='linear', C=1, random_state=0)
scores = cross_validate(clf, iris.data, iris.target, scoring=scoring,cv=5)
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_precision_macro',
 'test_recall_macro',
 'train_precision_macro',
 'train_recall_macro']

In [18]:
scores['test_recall_macro']

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])